on:
  pull_request:
    types: [closed]
env:
    PRIVATE_KEY : ${{ secrets.PRIVATE_KEY  }}
    HOSTNAME : ${{ secrets.HOSTNAME  }}
    USER_NAME : ${{ secrets.USER_NAME  }}
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Execute SSH commmands on remote server
        uses: JimCronqvist/action-ssh@master
        with: 
          hosts: ${{ secrets.HOSTNAME  }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
          debug: false
          command: |
            cd bash_assignment
            
