on:
  pull_request:
    types: [closed]
env:
    PRIVATE_KEY : ${{ secrets.PRIVATE_KEY  }}
    HOSTNAME : ${{ secrets.HOSTNAME  }}
    USER_NAME : ${{ secrets.USER_NAME  }}
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.5.4
        with: 
            ssh-private-key: ${PRIVATE_KEY}
      - run: ssh -A -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} 'cd bash_assignment && git pull'
            
