on:
  pull_request:
    types: [closed]
env:
    PRIVATE_KEY : ${{ secrets.PRIVATE_KEY  }}
    HOSTNAME : ${{ secrets.HOSTNAME  }}
    USER_NAME : ${{ secrets.USER_NAME  }}
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: ls -a via ssh
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd backend_assignment
            git pull
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USER_NAME  }}
          privateKey: ${{ secrets.PRIVATE_KEY}}
            
